### PR TITLE
Frontend

### PR DESCRIPTION
**Pull request by wkukka1**
Added the signup and login functionality from the assignment.
Changes: 
- When opening the app the login page is seen first rather than the signup
- There is a button that switches from login to signup
- Changed the loggedInView to have an add stock button, net profit label, and logout button
What to do next:
- Add functionality for logout button 
- Change clear button so that there is a confirmation
- add button to switch from signup to login

### CODE REVIEW

**Comment by zdavid4525** [comment]
@wkukka1 there are too many missing imports for me to review manually. CommonUserFactory alone is missing 
`import entity.User;
import entity.UserFactory;
import entity.CommonUser;`
please fix and update when done

**Comment by zdavid4525** [comment]
Looks good in general (the app runs!), but just a few suggestions:
 - Make sure all unused imports/variable declarations have a purpose - there are quite a few unused imports/variables I commented (and also many more so please fix those too)
  - Please leaving meaningful, unambiguous comments. Comments may not be updated over time, and can grow to be misleading as more changes are made to the code (it's even worse when they start off misleading)
  - Please follow the official Java style/spacing guidelines listed here: https://www.oracle.com/java/technologies/javase/codeconventions-contents.html. Alternatively, I believe the hotkey for IntelliJ's auto-format is Ctrl-Alt-L on Windows
  - Please consider making smaller commits. This helps the reviewer follow along, and reduces instances where commit messages are misleading (and thus useless) - an example is in "Fixed some casting issues with clear users and added the users.csv", where you added a new method with no apparent connection to the commit
  - Please include tests for each new feature introduced (or plan on including tests in the future, as this PR is quite long)
 
 Please look over this list and make fixes where needed. Thanks!

**Comment by wkukka1** [comment]
- deleted all the unused import statements 
- reformatted the code so that it follows official java guidelines
- added comments to ambiguous code 
- Could not add tests since most of the code is gui instantiation

**Review by zdavid4525 — APPROVED** [review]
lgtm!

**Pull request merged**
