### PR TITLE
add-add-stock-date-field

### PR DESCRIPTION
**Pull request by zdavid4525**
- added field to take stock purchase date + validation for the input ticker symbol, date, and amount

### CODE REVIEW

**Comment by wkukka1** [comment]
Everything looks good. Implementing the validator in the view is corresponds with clean architecture allowing each layer to have their own validation logic. The styling and documentation is very clear and readable, but please consider some small changes. 

- In initMonthsToDays consider the case that it is a leap year and that February has 29 days instead of 28

- In StockFieldValidatorImpl if you create a private instance attributes for your patterns you wont have to compile the patterns everytime that the method is run

- If you have time create tests to make sure that the validation is working as intended even though this doesn't count as interactor code

**Comment by zdavid4525** [comment]
for initMonthsToDays, I propose we create an issue for handling leap years and table it for when the team has more bandwidth. at the moment, it's capped at 28 to prevent passing "impossible" values to the rest client layer (and then getting a 404 not found or some other bad code). 

i'll definitely create tests for the validator and open another pr when those are done. i'll also make the regex class attributes and rerequest your review - thanks!

**Comment by wkukka1** [comment]
Sounds like a plan!

For the StockFieldValidatorImpl if in the instance attribute you use Pattern.compile(*your pattern*) it would only compile the regular expression once instead of creating the regular expression everytime you run the method.

**Comment by alexlee27** [comment]
For the format of the date, wouldn't it be better to have it as YYYY-MM-DD instead of dd/mm/yyyy to be consistent with what the MarketStack API accepts?

**Review by wkukka1 — APPROVED** [review]
Looks good!

**Comment by zdavid4525** [comment]
@alexlee27 right now we're storing LocalDateTime in all objects for dates. we could pass YYYY-MM-DD but that would require converting LocalDateTime into YYYY-MM-DD in many places versus just having conversion where it might be required - also, I'm not 100% sure but I believe marketstack's api accepts LocalDateTime.toString as a query param "format".

**Pull request merged**
